# The final and most robust cloudbuild.yaml
steps:
  # Step 0: Build the image and push it to Artifact Registry in one command.
  # This replaces the separate 'docker build' and 'docker push' steps.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'builds'
      - 'submit'
      - '--tag'
      - 'us-central1-docker.pkg.dev/llmarena-466615/llmarean-frontend:$COMMIT_SHA'
      - '.'

  # Step 1: Deploy the container image (which was pushed in Step 0) to Cloud Run.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'llmarean-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/llmarena-466615/llmarean-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--update-secrets=OPENROUTER_API_KEY=OPENROUTER_API_KEY:latest'

options:
  logging: CLOUD_LOGGING_ONLY 