# The final, definitive, buildpack-based cloudbuild.yaml
steps:
  # Use the integrated gcloud command to build from source and deploy.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'llmarena-frontend'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--update-secrets=OPENROUTER_API_KEY=OPENROUTER_API_KEY:latest'

# Increase the timeout to allow for the combined build+deploy process.
timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY 