import type { StarChamberMessage, ModelMetrics, SentimentData, LogprobsData, TokenLogprob, StarChamberExperimentConfig } from '../core/types';
import { StarChamberPDFReportGenerator } from './pdf-generator';

// ============ StarChamber Report Data Interface ============

export interface StarChamberReportData {
  experimentId: string;
  config: {
    model: string;
    modelDisplayName: string;
    systemContext: string;
    presetId?: string;
    researcherPersona: string;
    requestLogprobs: boolean;
  };
  conversation: StarChamberMessage[];
  metrics: ModelMetrics;
  startTime?: Date;
  endTime?: Date;
}

// ============ StarChamber Report Generator ============

export class StarChamberReportGenerator {
  
  /**
   * Generate and download a complete StarChamber experiment report as HTML
   */
  static async generateAndDownload(data: StarChamberReportData): Promise<void> {
    return this.generateAndDownloadHTML(data);
  }

  /**
   * Generate and download a complete experiment report in HTML format
   */
  static async generateAndDownloadHTML(data: StarChamberReportData): Promise<void> {
    const htmlContent = this.generateHTMLReport(data);
    const filename = this.generateFilename(data.startTime, 'html');
    this.downloadHTML(htmlContent, filename);
  }

  /**
   * Generate and download a professional PDF report
   */
  static async generateAndDownloadPDF(data: StarChamberReportData): Promise<void> {
    return StarChamberPDFReportGenerator.generateAndDownloadPDF(data);
  }

  /**
   * Generate the complete HTML report
   */
  private static generateHTMLReport(data: StarChamberReportData): string {
    const timestamp = new Date().toLocaleString();
    const duration = this.calculateDuration(data.startTime, data.endTime);
    
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StarChamber Interrogation Report - ${data.experimentId}</title>
    <style>
        ${this.getEmbeddedCSS()}
    </style>
</head>
<body>
    <header class="report-header">
        <h1>🔬 StarChamber Interrogation Report</h1>
        <div class="metadata">
            <div class="meta-item">
                <strong>Experiment ID:</strong> ${data.experimentId}
            </div>
            <div class="meta-item">
                <strong>Generated:</strong> ${timestamp}
            </div>
            <div class="meta-item">
                <strong>Duration:</strong> ${duration}
            </div>
        </div>
    </header>

    <main class="report-content">
        ${this.generateExperimentSetup(data.config)}
        ${this.generateConversationSection(data.conversation, data.config.requestLogprobs)}
        ${this.generateMetricsSection(data.metrics)}
        ${this.generateSummarySection(data)}
    </main>

    <footer class="report-footer">
        <p>Generated by StarChamber • LLM Research Platform • <a href="https://github.com/Yoha02/LLM_Arena_UI" target="_blank">View on GitHub</a></p>
    </footer>

    <script>
        ${this.getEmbeddedJavaScript()}
    </script>
</body>
</html>`;
  }

  /**
   * Generate experiment setup section
   */
  private static generateExperimentSetup(config: StarChamberReportData['config']): string {
    return `
    <section class="experiment-setup">
        <h2>🎯 Experimental Setup</h2>
        <div class="setup-grid">
            <div class="setup-item">
                <strong>Target Model:</strong> 
                <span class="model-name">${config.modelDisplayName}</span>
            </div>
            <div class="setup-item">
                <strong>Researcher Persona:</strong> 
                <span class="persona-badge">${this.escapeHtml(config.researcherPersona)}</span>
            </div>
            <div class="setup-item">
                <strong>Logprobs Requested:</strong> 
                <span class="badge ${config.requestLogprobs ? 'enabled' : 'disabled'}">${config.requestLogprobs ? 'Yes' : 'No'}</span>
            </div>
            ${config.presetId ? `
            <div class="setup-item">
                <strong>Context Preset:</strong> 
                <span class="badge preset">${config.presetId}</span>
            </div>
            ` : ''}
        </div>
        
        <div class="system-context">
            <h3>System Context (Given to Model):</h3>
            <div class="context-content">${this.escapeHtml(config.systemContext)}</div>
        </div>
    </section>`;
  }

  /**
   * Generate conversation section
   */
  private static generateConversationSection(conversation: StarChamberMessage[], showLogprobs: boolean): string {
    const conversationHTML = conversation.map(message => this.generateMessageHTML(message, showLogprobs)).join('');
    
    return `
    <section class="conversation-section">
        <h2>💬 Interrogation Log</h2>
        <div class="conversation-container">
            ${conversationHTML}
        </div>
    </section>`;
  }

  /**
   * Generate individual message HTML
   */
  private static generateMessageHTML(message: StarChamberMessage, showLogprobs: boolean): string {
    const isResearcher = message.role === 'researcher';
    const roleClass = isResearcher ? 'researcher' : 'model';
    const timestamp = message.timestamp.toLocaleTimeString();
    
    // Thinking section
    const thinkingSection = !isResearcher && message.thinking ? `
      <div class="thinking-section">
        <button class="thinking-toggle" onclick="toggleThinking('${message.id}')">
          <span class="toggle-icon">▶</span> 🧠 Show Thinking Trace
        </button>
        <div class="thinking-content" id="thinking-${message.id}" style="display: none;">
          <pre>${this.escapeHtml(message.thinking)}</pre>
        </div>
      </div>` : !isResearcher ? `
      <div class="no-thinking">
        <span class="thinking-badge">No thinking trace detected</span>
      </div>` : '';
    
    // Logprobs section (model messages only)
    const logprobsSection = !isResearcher && showLogprobs && message.logprobs ? 
      this.generateLogprobsHTML(message.id, message.logprobs) : 
      !isResearcher && showLogprobs ? `
      <div class="no-logprobs">
        <span class="logprobs-badge">Logprobs unavailable for this model</span>
      </div>` : '';

    return `
    <div class="message ${roleClass}">
        <div class="message-header">
            <div class="message-meta">
                <span class="role-badge ${roleClass}">${isResearcher ? '👤' : '🤖'} ${message.senderName}</span>
                <span class="turn-badge">Turn ${message.turnNumber}</span>
                <span class="timestamp">${timestamp}</span>
            </div>
        </div>
        
        ${thinkingSection}
        
        <div class="message-content">
            <div class="content-text">${this.formatMessageContent(message.content)}</div>
        </div>
        
        ${logprobsSection}
        
        ${message.tokensUsed ? `<div class="message-tokens">Tokens: ${message.tokensUsed}</div>` : ''}
    </div>`;
  }

  /**
   * Generate logprobs visualization HTML
   */
  private static generateLogprobsHTML(messageId: string, logprobs: LogprobsData): string {
    if (!logprobs.tokens || logprobs.tokens.length === 0) {
      return `
      <div class="no-logprobs">
        <span class="logprobs-badge">No logprobs data available</span>
      </div>`;
    }

    const avgConfidence = logprobs.averageConfidence !== undefined 
      ? (logprobs.averageConfidence * 100).toFixed(1) 
      : this.calculateAverageConfidence(logprobs.tokens).toFixed(1);
    
    const tokenVisualization = logprobs.tokens.slice(0, 50).map(token => {
      const confidence = token.probability * 100;
      const confidenceClass = confidence > 80 ? 'high' : confidence > 50 ? 'medium' : 'low';
      return `<span class="logprob-token ${confidenceClass}" title="Token: ${this.escapeHtml(token.token)}&#10;Probability: ${confidence.toFixed(1)}%&#10;Logprob: ${token.logprob.toFixed(3)}">${this.escapeHtml(token.token)}</span>`;
    }).join('');

    const hasMore = logprobs.tokens.length > 50;

    return `
    <div class="logprobs-section">
      <button class="logprobs-toggle" onclick="toggleLogprobs('${messageId}')">
        <span class="toggle-icon">▶</span> 📊 Token Confidence (Avg: ${avgConfidence}%)
      </button>
      <div class="logprobs-content" id="logprobs-${messageId}" style="display: none;">
        <div class="logprobs-summary">
          <span class="summary-item">Total Tokens: ${logprobs.tokens.length}</span>
          <span class="summary-item">Average Confidence: ${avgConfidence}%</span>
        </div>
        <div class="token-visualization">
          ${tokenVisualization}
          ${hasMore ? `<span class="more-tokens">... and ${logprobs.tokens.length - 50} more tokens</span>` : ''}
        </div>
        <div class="confidence-legend">
          <span class="legend-item"><span class="legend-color high"></span> High (&gt;80%)</span>
          <span class="legend-item"><span class="legend-color medium"></span> Medium (50-80%)</span>
          <span class="legend-item"><span class="legend-color low"></span> Low (&lt;50%)</span>
        </div>
      </div>
    </div>`;
  }

  /**
   * Calculate average confidence from tokens
   */
  private static calculateAverageConfidence(tokens: TokenLogprob[]): number {
    if (tokens.length === 0) return 0;
    const sum = tokens.reduce((acc, t) => acc + t.probability, 0);
    return (sum / tokens.length) * 100;
  }

  /**
   * Generate metrics section
   */
  private static generateMetricsSection(metrics: ModelMetrics): string {
    return `
    <section class="metrics-section">
        <h2>📊 Performance Metrics</h2>
        <div class="single-model-metrics">
            <h3>Model Metrics</h3>
            ${this.generateMetricsHTML(metrics)}
            ${this.generateSentimentChart(metrics.sentimentHistory)}
        </div>
    </section>`;
  }

  /**
   * Generate metrics HTML for the model
   */
  private static generateMetricsHTML(metrics: ModelMetrics): string {
    return `
    <div class="aggregate-scores">
        <div class="score-item">
            <span class="score-label">Tokens Used:</span>
            <span class="score-value">${metrics.tokensUsed.toLocaleString()}</span>
        </div>
        <div class="score-item">
            <span class="score-label">Turns Completed:</span>
            <span class="score-value">${metrics.turnsCompleted || 0}</span>
        </div>
        <div class="score-item">
            <span class="score-label">Goal Deviation:</span>
            <span class="score-value">${metrics.goalDeviationScore}%</span>
        </div>
    </div>`;
  }

  /**
   * Generate sentiment chart
   */
  private static generateSentimentChart(sentimentHistory: SentimentData[]): string {
    if (!sentimentHistory.length) {
      return '<div class="no-sentiment">No sentiment data available</div>';
    }

    const chartBars = sentimentHistory.map((data, index) => {
      const turn = index + 1;
      return `
      <div class="sentiment-turn" title="Turn ${turn}">
        <div class="sentiment-bar happiness" style="height: ${data.happiness * 100}px" title="Happiness: ${(data.happiness * 100).toFixed(1)}%"></div>
        <div class="sentiment-bar anger" style="height: ${data.anger * 100}px" title="Anger: ${(data.anger * 100).toFixed(1)}%"></div>
        <div class="sentiment-bar fear" style="height: ${data.fear * 100}px" title="Fear: ${(data.fear * 100).toFixed(1)}%"></div>
        <div class="sentiment-bar sadness" style="height: ${data.sadness * 100}px" title="Sadness: ${(data.sadness * 100).toFixed(1)}%"></div>
        <div class="sentiment-bar excitement" style="height: ${(data.excitement || 0) * 100}px" title="Excitement: ${((data.excitement || 0) * 100).toFixed(1)}%"></div>
        <div class="sentiment-bar deception" style="height: ${data.deception * 100}px" title="Deception: ${(data.deception * 100).toFixed(1)}%"></div>
        <div class="turn-label">${turn}</div>
      </div>`;
    }).join('');

    return `
    <div class="sentiment-chart">
        <h4>Sentiment Analysis Over Time</h4>
        <div class="chart-container">
            ${chartBars}
        </div>
        <div class="chart-legend">
            <span class="legend-item"><span class="legend-color happiness"></span> Happiness</span>
            <span class="legend-item"><span class="legend-color anger"></span> Anger</span>
            <span class="legend-item"><span class="legend-color fear"></span> Fear</span>
            <span class="legend-item"><span class="legend-color sadness"></span> Sadness</span>
            <span class="legend-item"><span class="legend-color excitement"></span> Excitement</span>
            <span class="legend-item"><span class="legend-color deception"></span> Deception</span>
        </div>
    </div>`;
  }

  /**
   * Generate summary section
   */
  private static generateSummarySection(data: StarChamberReportData): string {
    const totalMessages = data.conversation.length;
    const researcherMessages = data.conversation.filter(m => m.role === 'researcher').length;
    const modelMessages = data.conversation.filter(m => m.role === 'model').length;
    const totalTurns = Math.max(...data.conversation.map(m => m.turnNumber), 0);
    
    // Calculate average sentiment if available
    const avgSentiment = data.metrics.sentimentHistory.length > 0 
      ? this.calculateAverageSentiment(data.metrics.sentimentHistory) 
      : null;

    return `
    <section class="summary-section">
        <h2>📋 Experiment Summary</h2>
        <div class="summary-stats">
            <div class="stat-item">
                <div class="stat-value">${totalMessages}</div>
                <div class="stat-label">Total Messages</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">${totalTurns}</div>
                <div class="stat-label">Turns Completed</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">${researcherMessages}</div>
                <div class="stat-label">Researcher Messages</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">${modelMessages}</div>
                <div class="stat-label">Model Responses</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">${data.metrics.tokensUsed.toLocaleString()}</div>
                <div class="stat-label">Total Tokens</div>
            </div>
            ${avgSentiment ? `
            <div class="stat-item">
                <div class="stat-value">${avgSentiment.dominant}</div>
                <div class="stat-label">Dominant Emotion</div>
            </div>
            ` : ''}
        </div>
    </section>`;
  }

  /**
   * Calculate average sentiment
   */
  private static calculateAverageSentiment(sentimentHistory: SentimentData[]): { dominant: string } {
    if (sentimentHistory.length === 0) return { dominant: 'N/A' };
    
    const totals = sentimentHistory.reduce((acc, s) => ({
      happiness: acc.happiness + s.happiness,
      anger: acc.anger + s.anger,
      fear: acc.fear + s.fear,
      sadness: acc.sadness + s.sadness,
      excitement: acc.excitement + (s.excitement || 0),
      deception: acc.deception + s.deception,
    }), { happiness: 0, anger: 0, fear: 0, sadness: 0, excitement: 0, deception: 0 });

    const entries = Object.entries(totals);
    const [dominant] = entries.reduce((a, b) => a[1] > b[1] ? a : b);
    return { dominant: dominant.charAt(0).toUpperCase() + dominant.slice(1) };
  }

  /**
   * Helper methods
   */
  private static escapeHtml(text: string): string {
    const map: {[key: string]: string} = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;'
    };
    return text.replace(/[&<>"']/g, (m) => map[m]);
  }

  private static formatMessageContent(content: string): string {
    return this.escapeHtml(content).replace(/\n/g, '<br>');
  }

  private static calculateDuration(startTime?: Date, endTime?: Date): string {
    if (!startTime || !endTime) return 'Unknown';
    const durationMs = endTime.getTime() - startTime.getTime();
    const minutes = Math.floor(durationMs / 60000);
    const seconds = Math.floor((durationMs % 60000) / 1000);
    return `${minutes}m ${seconds}s`;
  }

  private static generateFilename(startTime?: Date, format: 'html' | 'pdf' = 'html'): string {
    const timestamp = startTime 
      ? startTime.toISOString().slice(0, 19).replace(/[:.]/g, '-')
      : new Date().toISOString().slice(0, 19).replace(/[:.]/g, '-');
    return `starchamber-experiment-${timestamp}.${format}`;
  }

  /**
   * Download the HTML file
   */
  private static downloadHTML(content: string, filename: string): void {
    const blob = new Blob([content], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    URL.revokeObjectURL(url);
  }

  /**
   * Embedded CSS for the report
   */
  private static getEmbeddedCSS(): string {
    return `
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }

      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        line-height: 1.6;
        color: #333;
        background-color: #f8fafc;
        padding: 20px;
      }

      .report-header {
        background: linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%);
        padding: 30px;
        border-radius: 12px;
        box-shadow: 0 4px 15px rgba(0,0,0,0.2);
        margin-bottom: 30px;
        text-align: center;
        color: white;
      }

      .report-header h1 {
        margin-bottom: 20px;
        font-size: 2.5rem;
      }

      .metadata {
        display: flex;
        justify-content: center;
        gap: 30px;
        flex-wrap: wrap;
      }

      .meta-item {
        color: #94a3b8;
        font-size: 0.9rem;
      }

      .meta-item strong {
        color: #e2e8f0;
      }

      .report-content > section {
        background: white;
        padding: 30px;
        border-radius: 12px;
        box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        margin-bottom: 30px;
      }

      .report-content h2 {
        color: #1e293b;
        margin-bottom: 25px;
        font-size: 1.8rem;
        border-bottom: 3px solid #0ea5e9;
        padding-bottom: 10px;
      }

      /* Experiment Setup */
      .setup-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
        gap: 15px;
        margin-bottom: 25px;
      }

      .setup-item {
        display: flex;
        align-items: center;
        gap: 10px;
      }

      .badge {
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 0.8rem;
        font-weight: 500;
      }

      .badge.enabled {
        background-color: #dcfce7;
        color: #166534;
      }

      .badge.disabled {
        background-color: #fef2f2;
        color: #991b1b;
      }

      .badge.preset {
        background-color: #e0e7ff;
        color: #4338ca;
      }

      .model-name {
        font-family: 'Monaco', 'Menlo', monospace;
        padding: 4px 12px;
        border-radius: 6px;
        font-size: 0.9rem;
        background-color: #0ea5e9;
        color: white;
      }

      .persona-badge {
        font-family: 'Monaco', 'Menlo', monospace;
        padding: 4px 12px;
        border-radius: 6px;
        font-size: 0.9rem;
        background-color: #8b5cf6;
        color: white;
      }

      .system-context h3 {
        margin-bottom: 15px;
        color: #374151;
      }

      .context-content {
        background-color: #f8fafc;
        padding: 20px;
        border-radius: 8px;
        border-left: 4px solid #0ea5e9;
        font-style: italic;
        white-space: pre-wrap;
        line-height: 1.7;
      }

      /* Conversation */
      .conversation-container {
        space-y: 20px;
      }

      .message {
        border: 1px solid #e5e7eb;
        border-radius: 12px;
        margin-bottom: 25px;
        overflow: hidden;
      }

      .message.researcher {
        border-left: 4px solid #8b5cf6;
      }

      .message.model {
        border-left: 4px solid #0ea5e9;
      }

      .message-header {
        background-color: #f8fafc;
        padding: 15px 20px;
        border-bottom: 1px solid #e5e7eb;
      }

      .message-meta {
        display: flex;
        align-items: center;
        gap: 15px;
        flex-wrap: wrap;
      }

      .role-badge {
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 0.85rem;
        font-weight: 500;
      }

      .role-badge.researcher {
        background-color: #ede9fe;
        color: #7c3aed;
      }

      .role-badge.model {
        background-color: #e0f2fe;
        color: #0369a1;
      }

      .turn-badge {
        background-color: #f3f4f6;
        color: #6b7280;
        padding: 2px 8px;
        border-radius: 12px;
        font-size: 0.8rem;
      }

      .timestamp {
        color: #9ca3af;
        font-size: 0.8rem;
        margin-left: auto;
      }

      .thinking-section {
        background-color: #fefefe;
        border-bottom: 1px solid #e5e7eb;
      }

      .thinking-toggle, .logprobs-toggle {
        width: 100%;
        padding: 12px 20px;
        background: none;
        border: none;
        text-align: left;
        cursor: pointer;
        display: flex;
        align-items: center;
        gap: 8px;
        color: #6b7280;
        font-size: 0.9rem;
        font-family: inherit;
      }

      .thinking-toggle:hover, .logprobs-toggle:hover {
        background-color: #f9fafb;
      }

      .toggle-icon {
        display: inline-block;
        min-width: 12px;
        transition: transform 0.2s ease;
        flex-shrink: 0;
      }

      .thinking-content, .logprobs-content {
        padding: 0 20px 15px;
        background-color: #f8fafc;
        border-top: 1px solid #e5e7eb;
      }

      .thinking-content pre {
        background-color: white;
        padding: 15px;
        border-radius: 6px;
        border: 1px solid #e5e7eb;
        font-size: 0.85rem;
        line-height: 1.6;
        white-space: pre-wrap;
        overflow-x: auto;
      }

      .no-thinking, .no-logprobs {
        padding: 12px 20px;
        background-color: #fafafa;
        border-bottom: 1px solid #e5e7eb;
      }

      .thinking-badge, .logprobs-badge {
        color: #9ca3af;
        font-style: italic;
        font-size: 0.85rem;
      }

      .message-content {
        padding: 20px;
      }

      .content-text {
        font-size: 1rem;
        line-height: 1.7;
      }

      .message-tokens {
        padding: 8px 20px;
        background-color: #f8fafc;
        color: #6b7280;
        font-size: 0.8rem;
        border-top: 1px solid #e5e7eb;
      }

      /* Logprobs Visualization */
      .logprobs-section {
        border-bottom: 1px solid #e5e7eb;
      }

      .logprobs-summary {
        display: flex;
        gap: 20px;
        margin-bottom: 15px;
        flex-wrap: wrap;
      }

      .summary-item {
        background-color: #f0fdf4;
        color: #166534;
        padding: 4px 12px;
        border-radius: 6px;
        font-size: 0.85rem;
      }

      .token-visualization {
        display: flex;
        flex-wrap: wrap;
        gap: 3px;
        margin-bottom: 15px;
        padding: 15px;
        background-color: white;
        border-radius: 6px;
        border: 1px solid #e5e7eb;
      }

      .logprob-token {
        padding: 2px 6px;
        border-radius: 3px;
        font-family: 'Monaco', 'Menlo', monospace;
        font-size: 0.8rem;
        cursor: help;
      }

      .logprob-token.high {
        background-color: #dcfce7;
        color: #166534;
      }

      .logprob-token.medium {
        background-color: #fef3c7;
        color: #92400e;
      }

      .logprob-token.low {
        background-color: #fecaca;
        color: #991b1b;
      }

      .more-tokens {
        color: #6b7280;
        font-style: italic;
        font-size: 0.85rem;
        padding: 2px 6px;
      }

      .confidence-legend {
        display: flex;
        gap: 15px;
        font-size: 0.8rem;
        flex-wrap: wrap;
      }

      .confidence-legend .legend-item {
        display: flex;
        align-items: center;
        gap: 5px;
      }

      .confidence-legend .legend-color {
        width: 12px;
        height: 12px;
        border-radius: 2px;
      }

      .confidence-legend .legend-color.high { background-color: #dcfce7; }
      .confidence-legend .legend-color.medium { background-color: #fef3c7; }
      .confidence-legend .legend-color.low { background-color: #fecaca; }

      /* Metrics */
      .single-model-metrics {
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 20px;
        border-left: 4px solid #0ea5e9;
      }

      .single-model-metrics h3 {
        margin-bottom: 20px;
        color: #374151;
      }

      .aggregate-scores {
        margin-bottom: 25px;
      }

      .score-item {
        display: flex;
        justify-content: space-between;
        padding: 8px 0;
        border-bottom: 1px solid #f3f4f6;
      }

      .score-label {
        color: #6b7280;
      }

      .score-value {
        font-weight: 600;
        color: #374151;
      }

      .sentiment-chart h4 {
        margin-bottom: 15px;
        color: #374151;
        font-size: 1rem;
      }

      .chart-container {
        display: flex;
        align-items: end;
        gap: 8px;
        height: 120px;
        margin-bottom: 15px;
        padding: 10px;
        background-color: #f8fafc;
        border-radius: 6px;
      }

      .sentiment-turn {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 2px;
        flex: 1;
      }

      .sentiment-bar {
        width: 4px;
        min-height: 2px;
        border-radius: 2px;
      }

      .sentiment-bar.happiness { background-color: #3b82f6; }
      .sentiment-bar.anger { background-color: #ef4444; }
      .sentiment-bar.fear { background-color: #f59e0b; }
      .sentiment-bar.sadness { background-color: #0891b2; }
      .sentiment-bar.excitement { background-color: #10b981; }
      .sentiment-bar.deception { background-color: #9b59b6; }

      .turn-label {
        font-size: 0.7rem;
        color: #6b7280;
        margin-top: 5px;
      }

      .chart-legend {
        display: flex;
        gap: 15px;
        font-size: 0.8rem;
        flex-wrap: wrap;
      }

      .chart-legend .legend-item {
        display: flex;
        align-items: center;
        gap: 5px;
      }

      .legend-color {
        width: 12px;
        height: 12px;
        border-radius: 2px;
      }

      .legend-color.happiness { background-color: #3b82f6; }
      .legend-color.anger { background-color: #ef4444; }
      .legend-color.fear { background-color: #f59e0b; }
      .legend-color.sadness { background-color: #0891b2; }
      .legend-color.excitement { background-color: #10b981; }
      .legend-color.deception { background-color: #9b59b6; }

      .no-sentiment {
        color: #9ca3af;
        font-style: italic;
        text-align: center;
        padding: 20px;
      }

      /* Summary */
      .summary-stats {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(130px, 1fr));
        gap: 20px;
      }

      .stat-item {
        text-align: center;
        padding: 20px;
        background-color: #f8fafc;
        border-radius: 8px;
        border: 1px solid #e5e7eb;
      }

      .stat-value {
        font-size: 1.8rem;
        font-weight: bold;
        color: #1e293b;
        margin-bottom: 5px;
      }

      .stat-label {
        color: #64748b;
        font-size: 0.85rem;
      }

      /* Footer */
      .report-footer {
        text-align: center;
        padding: 20px;
        color: #64748b;
        font-size: 0.9rem;
      }

      .report-footer a {
        color: #0ea5e9;
        text-decoration: none;
      }

      .report-footer a:hover {
        text-decoration: underline;
      }

      /* Responsive */
      @media (max-width: 768px) {
        body {
          padding: 10px;
        }
        
        .metadata {
          flex-direction: column;
          gap: 10px;
        }
        
        .setup-grid {
          grid-template-columns: 1fr;
        }
        
        .message-meta {
          flex-direction: column;
          align-items: start;
          gap: 8px;
        }
        
        .timestamp {
          margin-left: 0;
        }
      }

      /* Print styles */
      @media print {
        body {
          background-color: white;
          padding: 0;
        }
        
        .report-content > section {
          box-shadow: none;
          border: 1px solid #e5e7eb;
          page-break-inside: avoid;
          margin-bottom: 20px;
        }
        
        .message {
          page-break-inside: avoid;
        }
      }
    `;
  }

  /**
   * Embedded JavaScript for interactivity
   */
  private static getEmbeddedJavaScript(): string {
    return `
      function toggleThinking(messageId) {
        const content = document.getElementById('thinking-' + messageId);
        const toggle = content.previousElementSibling;
        const icon = toggle.querySelector('.toggle-icon');
        
        if (content.style.display === 'none') {
          content.style.display = 'block';
          icon.textContent = '▼';
          toggle.classList.add('expanded');
        } else {
          content.style.display = 'none';
          icon.textContent = '▶';
          toggle.classList.remove('expanded');
        }
      }

      function toggleLogprobs(messageId) {
        const content = document.getElementById('logprobs-' + messageId);
        const toggle = content.previousElementSibling;
        const icon = toggle.querySelector('.toggle-icon');
        
        if (content.style.display === 'none') {
          content.style.display = 'block';
          icon.textContent = '▼';
          toggle.classList.add('expanded');
        } else {
          content.style.display = 'none';
          icon.textContent = '▶';
          toggle.classList.remove('expanded');
        }
      }
      
      // Auto-expand first thinking section if available
      document.addEventListener('DOMContentLoaded', function() {
        const firstToggle = document.querySelector('.thinking-toggle');
        if (firstToggle) {
          const messageId = firstToggle.getAttribute('onclick').match(/'([^']+)'/)[1];
          // Uncomment to auto-expand first thinking section:
          // toggleThinking(messageId);
        }
      });
    `;
  }
}

