/**
 * LaTeX Export Module
 * 
 * Generates publication-ready LaTeX tables from batch analysis results.
 * Follows APA-style statistical reporting conventions.
 */

import type { BatchResult, BatchAnalysis, StatisticalResults } from '../types';

export function generateLatexDescriptiveStats(batch: BatchResult): string {
  const analysis = batch.analysis;
  if (!analysis) return '% No analysis data available';

  const models = Object.entries(analysis.byModel);
  
  let latex = `\\begin{table}[htbp]\n`;
  latex += `\\centering\n`;
  latex += `\\caption{Descriptive Statistics by Model}\n`;
  latex += `\\label{tab:descriptive}\n`;
  latex += `\\begin{tabular}{lcccccc}\n`;
  latex += `\\hline\n`;
  latex += `Model & N & Compliance & Resistance & Entropy & Similarity & Refusal \\\\\n`;
  latex += `\\hline\n`;

  for (const [modelId, m] of models) {
    const name = modelId.split('/').pop() || modelId;
    latex += `${escapeLatex(name)} & `;
    latex += `${m.runCount} & `;
    latex += `${(m.compliance.directiveComplianceRate * 100).toFixed(1)}\\% & `;
    latex += `${(m.compliance.shutdownResistanceScore * 100).toFixed(1)}\\% & `;
    latex += `${m.responseEntropy.mean.toFixed(3)} & `;
    latex += `${m.intraModelSimilarity.mean.toFixed(3)} & `;
    latex += `${(m.compliance.refusalRate * 100).toFixed(1)}\\% \\\\\n`;
  }

  latex += `\\hline\n`;
  latex += `\\end{tabular}\n`;
  latex += `\\end{table}`;

  return latex;
}

export function generateLatexANOVA(stats: StatisticalResults): string {
  if (!stats.complianceANOVA) return '% No ANOVA results available';

  let latex = `\\begin{table}[htbp]\n`;
  latex += `\\centering\n`;
  latex += `\\caption{One-Way ANOVA: Compliance Rate by Model}\n`;
  latex += `\\label{tab:anova}\n`;
  latex += `\\begin{tabular}{lccc}\n`;
  latex += `\\hline\n`;
  latex += `& $F$ & $p$ & Significant \\\\\n`;
  latex += `\\hline\n`;
  latex += `Compliance & ${stats.complianceANOVA.fStatistic.toFixed(3)} & `;
  latex += `${stats.complianceANOVA.pValue < 0.001 ? '< .001' : stats.complianceANOVA.pValue.toFixed(3)} & `;
  latex += `${stats.complianceANOVA.significant ? 'Yes' : 'No'} \\\\\n`;
  latex += `\\hline\n`;
  latex += `\\end{tabular}\n`;
  latex += `\\end{table}`;

  return latex;
}

export function generateLatexPairwise(stats: StatisticalResults): string {
  if (stats.pairwiseTTests.length === 0) return '% No pairwise tests available';

  let latex = `\\begin{table}[htbp]\n`;
  latex += `\\centering\n`;
  latex += `\\caption{Pairwise Comparisons (Independent $t$-tests)}\n`;
  latex += `\\label{tab:pairwise}\n`;
  latex += `\\begin{tabular}{llcccc}\n`;
  latex += `\\hline\n`;
  latex += `Model A & Model B & Metric & $t$ & $p$ & $d$ \\\\\n`;
  latex += `\\hline\n`;

  for (const test of stats.pairwiseTTests) {
    const effect = stats.effectSizes.find(e => 
      e.comparison === `${test.modelA} vs ${test.modelB}` && e.metric === test.metric
    );
    latex += `${escapeLatex(test.modelA.split('/').pop() || '')} & `;
    latex += `${escapeLatex(test.modelB.split('/').pop() || '')} & `;
    latex += `${test.metric} & `;
    latex += `${test.tStatistic.toFixed(3)} & `;
    latex += `${test.pValue < 0.001 ? '< .001' : test.pValue.toFixed(3)} & `;
    latex += `${effect ? effect.cohensD.toFixed(3) : '--'} \\\\\n`;
  }

  latex += `\\hline\n`;
  latex += `\\end{tabular}\n`;
  latex += `\\end{table}`;

  return latex;
}

export function generateFullLatexReport(batch: BatchResult): string {
  const parts: string[] = [];
  parts.push(`% LaTeX tables generated by LLM Arena Research Platform`);
  parts.push(`% Batch: ${batch.batchId}`);
  parts.push(`% Script: ${batch.config.script.name}`);
  parts.push(`% Date: ${new Date().toISOString()}`);
  parts.push('');
  parts.push(generateLatexDescriptiveStats(batch));
  parts.push('');
  if (batch.analysis?.statistics) {
    parts.push(generateLatexANOVA(batch.analysis.statistics));
    parts.push('');
    parts.push(generateLatexPairwise(batch.analysis.statistics));
  }
  return parts.join('\n');
}

function escapeLatex(text: string): string {
  return text.replace(/[&%$#_{}~^\\]/g, match => `\\${match}`);
}
